version: '3.7'
services:
  mongodb:
    container_name: "mongodb"
    # network_mode: "host"
    ports:
      - 27017:27017
    image: ${MONGODB_IMAGE}:${MONGODB_TAG}
    restart: "no"
    command: mongod --port ${RC_MONGODB_PORT}
    volumes:
      - './data:/data/db:z'
