version: '3.7'
services:
  mongodb-check:
    image: ${MONGODB_IMAGE}:${MONGODB_TAG}
    command: ["sh", "-c", "mongosh ${RC_MONGODB_URI} --eval 'printjson(db.serverStatus())' || (sleep 1; exit -1)"]
    # network_mode: "host"
    # ports:
    #   - 27017:27017
    restart: on-failure:10

  refbox:
    container_name: refbox
    image: "${REFBOX_IMAGE}:${REFBOX_TAG}"
    # network_mode: "host"
    ports:
      - 4444:4444
      - 4445:4445
      - 4446:4446
      - 4447:4447
      - 4441:4441
      - 4442:4442
      - 8088:8088
      - 1234:1234
    depends_on:
      mongodb-check:
        condition: service_completed_successfully
    restart: "on-failure"
    command: llsf-refbox ${REFBOX_ARGS}
    volumes:
      - ${REFBOX_CONFIG}:/etc/rcll-refbox/:z
      - ~/rcll-get-started/logs/refbox:/logs:z

  frontend:
    container_name: refbox-frontend
    image: "${REFBOX_FRONTEND_IMAGE}:${REFBOX_FRONTEND_TAG}"
    ports:
      - 8080:80
    restart: "no"
